name: CI Lint & Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**
  pull_request:
    paths:
      - src/**
      - tests/**
      - .github/workflows/**

jobs:
  web-ext-lint:
    name: "Web Ext Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "web-ext lint"
        uses: kewisch/action-web-ext@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cmd: lint
          source: src
          channel: listed
          verbose: true

  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npx eslint src

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Setup package & env
      run: npm run build --if-present
    - name: Run tests
      env:
        CI: true
      run: npm test
