name: CD Update version and publish to stores
on:
  workflow_dispatch:
    inputs:
      newAddonVersion:
        description: 'Please input version number in this format(YY.MM.DD): 21.07.31'
        required: true
jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Update version
        run: |
          cd ${{ github.workspace }}/src/
          sed -i'' -e 's|"version":.*|"version": "${{ github.event.inputs.newAddonVersion }}",|' manifest.json
          cat manifest.json
      # - name: Commit new version
      #   run: git remote set-url origin ${{ secrets.ssh }}
      #   run: git status
      #   run: git add .
      #   run: git commit -m "Auto updating TODO.txt"
      #   run: git fetch origin master
      #   run: git push origin HEAD:master
      - name: Zip it! zip it good!
        run: |
          mkdir ../build
          zip -r ../build/release.zip .
          pwd
          ls -la ../build/release.zip
