name: CD Update version and publish to stores
on:
  workflow_dispatch:
    inputs:
      newAddonVersion:
        description: 'Please input version number in this format(YY.MM.DD.XX): 21.12.31.01'
        required: true

jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - name: Show who executed this
        run: echo "${{ github.event.sender.login }}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Update version
        run: |
          cd ${{ github.workspace }}/src/
          echo "New Version: ${{ github.event.inputs.newAddonVersion }}"
          sed -i'' -e 's|"version":.*|"version": "${{ github.event.inputs.newAddonVersion }}",|' manifest.json
          cat manifest.json

      - name: Commit new version
        run: |
          # run: git remote set-url origin ${{ secrets.ssh }}
          git status
          git diff
          git add src/manifest.json
          git commit -m "Auto updating version"
          git push origin HEAD:master
      - name: Zip it! zip it good!
        run: |
          cd ${{ github.workspace }}/src/
          mkdir ../build
          zip -r ../build/release.zip .
          pwd
          ls -la ../build/release.zip
