name: "CD Update version and publish to stores"
on:
  workflow_dispatch:
    # inputs:
      # newAddonVersion:
        # description: 'Please input version number (yy.m.x) (no leading zeros): 21.12.1'
        # required: true

jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - name: Show who executed this
        run: echo "${{ github.event.sender.login }}"

      - name: Check out repository code
        uses: actions/checkout@v2
        # with:
        #   fetch-depth: '0'

      - name: Pull in latest Tsitus tools
        run: |
          cd ${{ github.workspace }}/src/
          mkdir -p third_party/tsitu
          cd third_party/tsitu
          curl -O -J https://cdn.jsdelivr.net/gh/tsitu/MH-Tools@master/src/bookmarklet/bm-analyzer.min.js
          curl -O -J https://cdn.jsdelivr.net/gh/tsitu/MH-Tools@master/src/bookmarklet/bm-crafting.min.js
          curl -O -J https://cdn.jsdelivr.net/gh/tsitu/MH-Tools@master/src/bookmarklet/bm-cre.min.js
          curl -O -J https://cdn.jsdelivr.net/gh/tsitu/MH-Tools@master/src/bookmarklet/bm-crown.min.js
          curl -O -J https://cdn.jsdelivr.net/gh/tsitu/MH-Tools@master/src/bookmarklet/bm-map.min.js
          curl -O -J https://cdn.jsdelivr.net/gh/tsitu/MH-Tools@master/src/bookmarklet/bm-menu.min.js
          curl -O -J https://cdn.jsdelivr.net/gh/tsitu/MH-Tools@master/src/bookmarklet/bm-powers.min.js
          curl -O -J https://cdn.jsdelivr.net/gh/tsitu/MH-Tools@master/src/bookmarklet/bm-setup-fields.min.js
          curl -O -J https://cdn.jsdelivr.net/gh/tsitu/MH-Tools@master/src/bookmarklet/bm-setup-items.min.js
          ls -la

      - name: Check if there are changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11

      - name: Commit new version
        if: steps.changes.outputs.changed == 1
        run: |
          git config --global user.name 'CD Publish Job'
          git config --global user.email 'CD_Publish_Job@users.noreply.github.com'
          git add src/manifest.json
          git commit -m "Automated tsitus tools update"
          git push

      - name: Bump version and push tag
        id: bump_version
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # WITH_V: false
          DRY_RUN: true
          DEFAULT_BUMP: "patch"

      - name: Update version
        run: |
          cd ${{ github.workspace }}/src/
          echo "New Version: ${{ steps.bump_version.outputs.tag }}"
          sed -i'' -e 's|"version":.*|"version": "${{ steps.bump_version.outputs.tag }}",|' manifest.json
          cat manifest.json

      # - name: Zip it! zip it good!
      #   run: |
      #     cd ${{ github.workspace }}/src/
      #     mkdir ../build
      #     zip -r ../build/release.zip .
      #     pwd
      #     ls -la ../build/release.zip
      #     cd ../
      #
      # - name: Upload new release zip to Chrome Webstore
      #   uses: Klemensas/chrome-extension-upload-action@1df3cdf4047a4789bc61a64a125994d8caf23572
      #   with:
      #     refresh-token: ${{ secrets.CHROME_WEBSTORE_REFRESH_TOKEN }}
      #     client-id: ${{ secrets.CHROME_WEBSTORE_CLIENT_ID }}
      #     client-secret: ${{ secrets.CHROME_WEBSTORE_CLIENT_SECRET }}
      #     file-name: './build/release.zip'
      #     app-id: 'ghfmjkamilolkalibpmokjigalmncfek'
      #     publish: true
      #
      # - name: Rename zip to xpi
      #   run: |
      #     mv build/release.zip build/release.xpi
      #     ls -la build/release.xpi
      #
      # - name: Upload new release xpi to Firefox Webstore
      #   uses: trmcnvn/firefox-addon@b2d90798a21626e1f4f25ffa279ba2e7199bb4cc
      #   with:
      #     uuid: '{801e5516-3311-4ee7-8185-7da12ffab807}'
      #     xpi: ./build/release.xpi
      #     manifest: ./src/manifest.json
      #     api-key: ${{ secrets.FIREFOX_WEBSTORE_API_KEY }}
      #     api-secret: ${{ secrets.FIREFOX_WEBSTORE_API_SECRET }}
      #   env:
      #     VERSION: ${{ github.event.inputs.newAddonVersion }}
